import { createContext, useContext, useState, useEffect, useMemo } from 'react';

const LanguageContext = createContext(null);

const LANG_KEY = 'ethereal-lang';

const translations = {
  en: {
    navHome: 'Home',
    navTrips: 'Trips',
    navBlog: 'Blog',
    navContact: 'Contact',
    navDashboard: 'Dashboard',
    navLogin: 'Login',
    navLogout: 'Logout',
    search: 'Search',
    searchPlaceholder: 'Search by trip name or description...',
    destination: 'Destination',
    allDestinations: 'All Destinations',
    tripType: 'Trip Type',
    allTypes: 'All Types',
    minPrice: 'Min Price',
    maxPrice: 'Max Price',
    includeInactive: 'Include Inactive',
    duration: 'Duration',
    adultPrice: 'Adult Price',
    childPrice: 'Child Price',
    availableDays: 'Available Days',
    timeFrom: 'Time From',
    days: 'days',
    bookNow: 'Book Now',
    noTrips: 'No trips found matching your filters.',
    errorLoading: 'Failed to fetch trips. Please check your connection.',
    previous: 'Previous',
    next: 'Next',
    pageSize: 'Page Size',
    tripDetails: 'Trip Details',
    backToTrips: 'Back to Trips',
    highlights: 'Highlights',
    includes: 'Includes',
    excludes: 'Excludes',
    whatToBring: 'What to Bring',
    status: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    adminPanel: 'Admin Panel',
    manageTrips: 'Manage Trips',
    createNewTrip: 'Create New Trip',
    editTrip: 'Edit Trip',
    uploadImages: 'Upload Images',
    setPrimary: 'Set Primary',
    delete: 'Delete',
    deactivate: 'Deactivate',
    reactivate: 'Reactivate',
    save: 'Save',
    cancel: 'Cancel',
    yes: 'Yes',
    no: 'No',
    confirmDelete: 'Are you sure you want to delete this?',
    loading: 'Loading...'
  },
  fr: {
    navHome: 'Accueil',
    navTrips: 'Voyages',
    navBlog: 'Blog',
    navContact: 'Contact',
    navDashboard: 'Tableau de bord',
    navLogin: 'Connexion',
    navLogout: 'Déconnexion',
    search: 'Rechercher',
    searchPlaceholder: 'Rechercher par nom ou description...',
    destination: 'Destination',
    allDestinations: 'Toutes les destinations',
    tripType: 'Type de voyage',
    allTypes: 'Tous les types',
    minPrice: 'Prix min',
    maxPrice: 'Prix max',
    includeInactive: 'Inclure les inactifs',
    duration: 'Durée',
    adultPrice: 'Prix adulte',
    childPrice: 'Prix enfant',
    availableDays: 'Jours disponibles',
    timeFrom: 'À partir de',
    days: 'jours',
    bookNow: 'Réserver',
    noTrips: 'Aucun voyage trouvé avec ces filtres.',
    errorLoading: 'Échec du chargement des voyages.',
    previous: 'Précédent',
    next: 'Suivant',
    pageSize: 'Taille de page',
    tripDetails: 'Détails du voyage',
    backToTrips: 'Retour aux voyages',
    highlights: 'Points forts',
    includes: 'Inclus',
    excludes: 'Exclus',
    whatToBring: 'À apporter',
    status: 'Statut',
    active: 'Actif',
    inactive: 'Inactif',
    adminPanel: 'Panel Admin',
    manageTrips: 'Gérer les voyages',
    createNewTrip: 'Créer un voyage',
    editTrip: 'Modifier le voyage',
    uploadImages: 'Télécharger des images',
    setPrimary: 'Définir comme principale',
    delete: 'Supprimer',
    deactivate: 'Désactiver',
    reactivate: 'Réactiver',
    save: 'Sauvegarder',
    cancel: 'Annuler',
    yes: 'Oui',
    no: 'Non',
    confirmDelete: 'Êtes-vous sûr de vouloir supprimer cela ?',
    loading: 'Chargement...'
  },
  ru: {
    navHome: 'Главная',
    navTrips: 'Поездки',
    navBlog: 'Блог',
    navContact: 'Контакты',
    navDashboard: 'Панель',
    navLogin: 'Войти',
    navLogout: 'Выйти',
    search: 'Поиск',
    searchPlaceholder: 'Поиск по названию или описанию...',
    destination: 'Направление',
    allDestinations: 'Все направления',
    tripType: 'Тип поездки',
    allTypes: 'Все типы',
    minPrice: 'Мин. цена',
    maxPrice: 'Макс. цена',
    includeInactive: 'Показать неактивные',
    duration: 'Длительность',
    adultPrice: 'Цена для взрослых',
    childPrice: 'Детский билет',
    availableDays: 'Доступные дни',
    timeFrom: 'Время начала',
    days: 'дней',
    bookNow: 'Забронировать',
    noTrips: 'Поездок по выбранным фильтрам не найдено.',
    errorLoading: 'Не удалось загрузить поездки.',
    previous: 'Назад',
    next: 'Вперед',
    pageSize: 'Размер страницы',
    tripDetails: 'Детали поездки',
    backToTrips: 'Назад к поездкам',
    highlights: 'Особенности',
    includes: 'Включено',
    excludes: 'Исключено',
    whatToBring: 'Что взять с собой',
    status: 'Статус',
    active: 'Активно',
    inactive: 'Неактивно',
    adminPanel: 'Панель админа',
    manageTrips: 'Управление поездками',
    createNewTrip: 'Создать поездку',
    editTrip: 'Редактировать поездку',
    uploadImages: 'Загрузить фото',
    setPrimary: 'Сделать главным',
    delete: 'Удалить',
    deactivate: 'Деактивировать',
    reactivate: 'Активировать',
    save: 'Сохранить',
    cancel: 'Отмена',
    yes: 'Да',
    no: 'Нет',
    confirmDelete: 'Вы уверены, что хотите удалить?',
    loading: 'Загрузка...'
  },
  de: {
    navHome: 'Startseite',
    navTrips: 'Reisen',
    navBlog: 'Blog',
    navContact: 'Kontakt',
    navDashboard: 'Dashboard',
    navLogin: 'Anmelden',
    navLogout: 'Abmelden',
    search: 'Suche',
    searchPlaceholder: 'Suche nach Name oder Beschreibung...',
    destination: 'Zielort',
    allDestinations: 'Alle Zielorte',
    tripType: 'Reiseart',
    allTypes: 'Alle Typen',
    minPrice: 'Mindestpreis',
    maxPrice: 'Maximalpreis',
    includeInactive: 'Inaktive einschließen',
    duration: 'Dauer',
    adultPrice: 'Erwachsenenpreis',
    childPrice: 'Kinderpreis',
    availableDays: 'Verfügbare Tage',
    timeFrom: 'Startzeit',
    days: 'Tage',
    bookNow: 'Jetzt buchen',
    noTrips: 'Keine Reisen für diese Filter gefunden.',
    errorLoading: 'Fehler beim Laden der Reisen.',
    previous: 'Zurück',
    next: 'Weiter',
    pageSize: 'Seitengröße',
    tripDetails: 'Reisedetails',
    backToTrips: 'Zurück zu den Reisen',
    highlights: 'Highlights',
    includes: 'Inklusive',
    excludes: 'Exklusive',
    whatToBring: 'Was mitzubringen ist',
    status: 'Status',
    active: 'Aktiv',
    inactive: 'Inaktiv',
    adminPanel: 'Admin-Bereich',
    manageTrips: 'Reisen verwalten',
    createNewTrip: 'Neue Reise erstellen',
    editTrip: 'Reise bearbeiten',
    uploadImages: 'Bilder hochladen',
    setPrimary: 'Als Hauptbild',
    delete: 'Löschen',
    deactivate: 'Deaktivieren',
    reactivate: 'Reaktivieren',
    save: 'Speichern',
    cancel: 'Abbrechen',
    yes: 'Ja',
    no: 'Nein',
    confirmDelete: 'Sind Sie sicher, dass Sie dies löschen möchten?',
    loading: 'Laden...'
  }
};

export default function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(() => {
    return localStorage.getItem(LANG_KEY) || 'en';
  });

  const setLanguage = (lang) => {
    if (translations[lang]) {
      setLanguageState(lang);
      localStorage.setItem(LANG_KEY, lang);
      // Force reload/trigger headers update or let the app re-render
    }
  };

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  const value = useMemo(() => ({ language, setLanguage, t }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
